Object.assign(L.en,{period:'Period',noData:'No data available yet.',first:'Create your first transaction',cash:'Cash / bank account',c1:'Income vs expenses',c2:'Expense breakdown',c3:'Income breakdown',c4:'Net worth trend',c5:'Assets vs liabilities',c6:'Top expense categories',c7:'Cash flow trend',income:'Income',expense:'Expenses',nw:'Net worth',in:'Money in',out:'Money out',ncf:'Net cash flow',noPer:'No data for this period.',noCash:'Mark an asset account as “Cash / bank account” to see cash flow.',p:['This month','Last month','Last 3 months','Last 6 months','Last 12 months','This year','Custom range'],tn:['Top 5','Top 10','All expenses']});
Object.assign(L.tl,{period:'Panahon',noData:'Wala pang datos.',first:'Gumawa ng unang transaksyon',cash:'Cash / bank na account',c1:'Kita vs gastos',c2:'Hati ng gastos',c3:'Hati ng kita',c4:'Takbo ng net worth',c5:'Ari-arian vs utang',c6:'Pinakamalalaking gastos',c7:'Takbo ng cash flow',income:'Kita',expense:'Gastos',nw:'Net worth',in:'Pumasok',out:'Lumabas',ncf:'Netong cash flow',noPer:'Walang datos sa panahong ito.',noCash:'Markahan ang isang asset account bilang “Cash / bank” para makita ang cash flow.',p:['Ngayong buwan','Nakaraang buwan','Huling 3 buwan','Huling 6 na buwan','Huling 12 buwan','Ngayong taon','Custom na saklaw'],tn:['Top 5','Top 10','Lahat ng gastos']});
const PV=['this','last','3m','6m','12m','year','custom'],PAL=['var(--g)','var(--pu)','var(--or)','#1b7ab8','var(--rd)','#8a6d1a','#6b7a8f'];let LR=null;
const pad=n=>String(n).padStart(2,'0'),ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const mlabel=k=>new Date(+k.slice(0,4),+k.slice(5)-1,1).toLocaleDateString(lang==='tl'?'fil-PH':'en-PH',{month:'short',year:'2-digit'});
const short=v=>'₱'+(Math.abs(v)>=1e6?(v/1e6).toFixed(1)+'M':Math.abs(v)>=1e3?(v/1e3).toFixed(Math.abs(v)>=1e4?0:1)+'k':Math.round(v));
function range(){const n=new Date(),y=n.getFullYear(),m=n.getMonth(),p=$('per').value||'6m',r=(a,b)=>[ymd(new Date(y,m+a,1)),ymd(new Date(y,m+b+1,0))];
 if(p==='custom')return[$('pf').value||`${y}-01-01`,$('pt').value||ymd(n)];
 return{this:r(0,0),last:r(-1,-1),'3m':r(-2,0),'6m':r(-5,0),'12m':r(-11,0),year:[`${y}-01-01`,`${y}-12-31`]}[p]||r(-5,0)}
function report(){let[from,to]=range();if(from>to)[from,to]=[to,from];return AC.compute(S.accounts,S.transactions,from,to)}
function xy(el,lab,bars,lines){const all=[...bars,...lines].flatMap(s=>s.vals),W=600,H=260,l=62,r=10,tp=10,b=32,n=lab.length,mx=Math.max(0,...all),mn=Math.min(0,...all),sp=(mx-mn)||1,
 y=v=>tp+(H-tp-b)*(1-(v-mn)/sp),bw=(W-l-r)/n,xc=i=>l+bw*(i+.5),col=(s,i)=>Array.isArray(s.color)?s.color[i]:s.color;let s=`<svg viewBox="0 0 ${W} ${H}" role="img">`;
 for(let i=0;i<=4;i++){const v=mn+sp*i/4;s+=`<line x1="${l}" x2="${W-r}" y1="${y(v)}" y2="${y(v)}" class="gl"/><text x="${l-6}" y="${y(v)+4}" text-anchor="end">${short(v)}</text>`}
 const st=Math.ceil(n/8);lab.forEach((q,i)=>{if(i%st===0)s+=`<text x="${xc(i)}" y="${H-10}" text-anchor="middle">${esc(q)}</text>`});
 const k=bars.length,w=Math.min(30,bw*.8/Math.max(k,1));
 bars.forEach((sr,j)=>sr.vals.forEach((v,i)=>{s+=`<rect x="${xc(i)-w*k/2+j*w}" y="${Math.min(y(v),y(0))}" width="${w-2}" height="${Math.abs(y(v)-y(0))||1}" rx="2" style="fill:${col(sr,i)}"/>`}));
 lines.forEach(sr=>{s+=`<polyline fill="none" stroke-width="2.5" style="stroke:${sr.color}" points="${sr.vals.map((v,i)=>xc(i)+','+y(v)).join(' ')}"/>`+sr.vals.map((v,i)=>`<circle cx="${xc(i)}" cy="${y(v)}" r="3.5" style="fill:${sr.color}"/>`).join('')});
 lab.forEach((q,i)=>{s+=`<rect x="${l+bw*i}" y="${tp}" width="${bw}" height="${H-tp-b}" fill="transparent" data-tip="${esc([q,...[...bars,...lines].map(z=>z.name+': '+money(z.vals[i]))].join('\n'))}"/>`});
 const lg=[...bars,...lines].filter(z=>!Array.isArray(z.color)).map(z=>`<span><i style="background:${z.color}"></i>${esc(z.name)}</span>`).join('');el.innerHTML=s+'</svg>'+(lg?`<div class="leg">${lg}</div>`:'')}
function list(items,tot){const mx=items[0]?.v||1;return items.map((o,i)=>{const p=(o.v/tot*100).toFixed(1);return`<button class="hb" data-acc="${o.id}" data-tip="${esc(o.name+'\n'+money(o.v)+' · '+p+'%')}"><span><i class="sw" style="background:${PAL[i%7]}"></i>${esc(o.name)}</span><span class="bar"><i style="width:${o.v/mx*100}%;background:${PAL[i%7]}"></i></span><b>${money(o.v)} <small>${p}%</small></b></button>`}).join('')}
const emptyMsg=(R,ty)=>{const n=R.issues.filter(i=>i.code==='abn'&&i.type===ty).length;return n?fmt(t('i_abx'),{n,ty}):t('noPer')};
function pie(el,items,R,ty){if(!items.length)return void(el.innerHTML=`<p>${emptyMsg(R,ty)}</p>`);const tot=items.reduce((s,o)=>s+o.v,0);
 if(items.length>6)return void(el.innerHTML=list(items,tot));let off=25,s='<svg viewBox="0 0 42 42" role="img"><circle cx="21" cy="21" r="15.9155" fill="none" stroke-width="7" style="stroke:var(--bg)"/>';
 items.forEach((o,i)=>{const p=o.v/tot*100;s+=`<circle cx="21" cy="21" r="15.9155" fill="none" stroke-width="7" stroke-dasharray="${p} ${100-p}" stroke-dashoffset="${off}" style="stroke:${PAL[i%7]}" data-acc="${o.id}" data-tip="${esc(o.name+'\n'+money(o.v)+' · '+p.toFixed(1)+'%')}"/>`;off-=p});
 el.innerHTML=`<div class="dn">${s}</svg><div>${list(items,tot)}</div></div>`}
function initCharts(){['per','pf','pt','topn'].forEach(id=>$(id).onchange=()=>render());$('first').onclick=()=>{$('tf').scrollIntoView();$('ta').focus()};
 const tip=$('tip')||Object.assign(document.body.appendChild(document.createElement('div')),{id:'tip'});
 ['pointermove','pointerdown'].forEach(ev=>document.addEventListener(ev,e=>{const el=e.target.closest&&e.target.closest('[data-tip]');if(!el){tip.style.display='none';return}tip.textContent=el.dataset.tip;tip.style.display='block';tip.style.left=Math.max(4,Math.min(e.clientX+12,innerWidth-tip.offsetWidth-8))+'px';tip.style.top=(e.clientY+14)+'px'}));
 document.addEventListener('click',e=>{const el=e.target.closest&&e.target.closest('[data-acc]');if(!el||!LR)return;$('fsel').value=el.dataset.acc;$('ff').value=LR.from;$('ft').value=LR.to;render();$('aout').scrollIntoView()})}
function drawCharts(R){LR=R;const p=$('per'),v=p.value||'6m',n=$('topn').value||'5';
 p.innerHTML=PV.map((k,i)=>`<option value="${k}">${t('p')[i]}</option>`).join('');p.value=v;$('topn').innerHTML=['5','10','0'].map((k,i)=>`<option value="${k}">${t('tn')[i]}</option>`).join('');$('topn').value=n;
 $('cust').classList.toggle('hidden',v!=='custom');if(v==='custom'){$('pf').value=R.from;$('pt').value=R.to}
 const has=S.transactions.length>0;$('empty').classList.toggle('hidden',has);$('charts').classList.toggle('hidden',!has);if(!has)return;
 const lab=R.months.map(mlabel),no=el=>el.innerHTML=`<p>${t('noPer')}</p>`;
 R.has?xy($('c1'),lab,[{name:t('income'),color:'var(--g)',vals:R.inc},{name:t('expense'),color:'var(--or)',vals:R.exp}],[]):no($('c1'));
 xy($('c4'),lab,[],[{name:t('nw'),color:'var(--pu)',vals:R.nw}]);
 pie($('c2'),R.expBy,R,'Expense');pie($('c3'),R.incBy,R,'Income');
 xy($('c5'),[t('assets'),t('liab')],[{name:'',color:['var(--g)','var(--pu)'],vals:[R.assets,R.liab]}],[]);
 if(!R.hasCash)$('c7').innerHTML=`<p>${t('noCash')}</p>`;else if(!R.has)no($('c7'));else xy($('c7'),lab,[{name:t('in'),color:'var(--g)',vals:R.cf.map(c=>c.in)},{name:t('out'),color:'var(--or)',vals:R.cf.map(c=>c.out)}],[{name:t('ncf'),color:'var(--pu)',vals:R.cf.map(c=>c.in-c.out)}]);
 const top=+n?R.expBy.slice(0,+n):R.expBy;top.length?$('c6').innerHTML=list(top,R.expPos):($('c6').innerHTML=`<p>${emptyMsg(R,'Expense')}</p>`)}
Object.assign(L.en,{is:'Income statement',bs:'Balance sheet',totInc:'Total income',totExp:'Total expenses',totA:'Total assets',totL:'Total liabilities',totE:'Total equity',earn:'Current & retained earnings',le:'Liabilities + equity',asof:'as of',ptag:'period',sd:'debit',sc:'credit',bad:'Check the amount, date and accounts.',noOpenPL:'Opening balances apply only to Asset, Liability and Equity accounts. Record prior income or expenses as dated entries.',okAll:'Books balanced: debits = credits and assets = liabilities + equity.',i_tb:'Trial balance is out of balance by {diff}. Accounts: {a}',i_bs:'Assets ≠ liabilities + equity (difference {diff}). Accounts: {a}',i_abn:'{n} ({ty}) has a {side} balance, opposite to its account type. Check the account type or its entries.',i_bad:'Entry {d} “{m}” is invalid ({r}) and is excluded from all totals.',i_dup:'Entry {d} “{m}” has a duplicate id and is excluded from all totals.',i_mig:'Opening balance of {n} ({v}) was converted to a journal entry against Opening Balance Equity, dated {d}.'});
Object.assign(L.tl,{is:'Income statement',bs:'Balance sheet',totInc:'Kabuuang kita',totExp:'Kabuuang gastos',totA:'Kabuuang ari-arian',totL:'Kabuuang utang',totE:'Kabuuang equity',earn:'Kita ngayon at naipon',le:'Utang + equity',asof:'hanggang',ptag:'panahon',sd:'debit',sc:'credit',bad:'Suriin ang halaga, petsa at mga account.',noOpenPL:'Ang panimulang balanse ay para lang sa Asset, Liability at Equity. Itala ang dating kita o gastos bilang entry na may petsa.',okAll:'Balanse ang libro: debit = credit at ari-arian = utang + equity.',i_tb:'Hindi balanse ang trial balance ng {diff}. Mga account: {a}',i_bs:'Ari-arian ≠ utang + equity (pagkakaiba {diff}). Mga account: {a}',i_abn:'Ang {n} ({ty}) ay may {side} na balanse, kabaligtaran ng uri nito. Suriin ang uri o mga entry.',i_bad:'Di-wasto ang entry {d} “{m}” ({r}); hindi ito kasama sa mga total.',i_dup:'May kaparehong id ang entry {d} “{m}”; hindi ito kasama sa mga total.',i_mig:'Ang panimulang balanse ng {n} ({v}) ay ginawang journal entry laban sa Opening Balance Equity, petsa {d}.'});
Object.assign(L.en,{i_abn:'{n} has a {side} balance of {amt}. {ty} accounts normally have {norm} balances. Review the account type or the entries below.',i_abx:'Nothing positive to chart. {n} {ty} account(s) have abnormal balances, see the warnings above.',swap:'Swap Dr/Cr',swapq:'Swap the debit and credit accounts of this entry? The amount and date stay the same.',otag:'opening entry'});
Object.assign(L.tl,{i_abn:'Ang {n} ay may {side} na balanse na {amt}. Ang {ty} ay karaniwang may {norm} na balanse. Suriin ang uri ng account o ang mga entry sa ibaba.',i_abx:'Walang positibong ipapakita. {n} na {ty} account ay may abnormal na balanse, tingnan ang mga babala sa itaas.',swap:'Ipagpalit ang Dr/Cr',swapq:'Ipagpalit ang debit at credit na account ng entry na ito? Hindi magbabago ang halaga at petsa.',otag:'panimulang entry'});
