import fs from 'node:fs';
const src = fs.readFileSync(new URL('../accounting.js', import.meta.url), 'utf8');
const { AC, delta, normalBalance } = new Function(src + ';return{AC,delta,normalBalance}')();
let fails = 0; const ok = (c, m) => { console.log(c ? 'ok  ' : 'FAIL', m); if (!c) fails++; };
const A = (id, type, x = {}) => ({ id, name: id, type, ...x });
const T = (id, dr, cr, amount, date = '2026-09-29') => ({ id, date, description: id, amount, debitAccountId: dr, creditAccountId: cr });
const run = (accts, txs) => AC.compute(accts, txs, '2026-09-01', '2026-09-30');
const abn = (R, n) => R.issues.find(i => i.code === 'abn' && i.name === n);
ok(['Asset','Expense'].every(t => normalBalance(t) === 'debit') && ['Liability','Equity','Income'].every(t => normalBalance(t) === 'credit'), 'Normal balances: Asset/Expense debit; Liability/Equity/Income credit');
let R = run([A('Cash','Asset'), A('Sales','Income')], [T('1','Cash','Sales',10000)]);
ok(R.end.Sales === 10000 && R.income === 10000 && !R.issues.length, 'Test 1 Income: Sales 10,000, no warning');
R = run([A('Cash','Asset'), A('Exp','Expense')], [T('1','Exp','Cash',3000)]);
ok(R.end.Exp === 3000 && R.expense === 3000 && !abn(R,'Exp'), 'Test 2 Expense: 3,000, no warning on Expense');
ok(abn(R,'Cash')?.side === 'credit', 'Unfunded cash (credit only) is flagged as abnormal, not hidden');
R = run([A('Cash','Asset'), A('Sales','Income'), A('Exp','Expense')], [T('1','Cash','Sales',10000), T('2','Exp','Cash',3000)]);
ok(R.income - R.expense === 7000 && R.end.Cash === 7000, 'Test 3 Net income 7,000');
R = run([A('Cash','Asset'), A('Loan','Liability')], [T('1','Cash','Loan',20000)]);
ok(R.end.Cash === 20000 && R.end.Loan === 20000 && R.assets === R.liab + R.equity, 'Test 4 Liability: Cash 20,000, Loan 20,000');
R = run([A('Cash','Asset'), A('Sales','Income')], [T('1','Sales','Cash',5000)]);
ok(abn(R,'Sales')?.side === 'debit' && abn(R,'Sales').amt === 5000, 'Test 5 Abnormal income: Sales has a debit balance of 5,000');
R = run([A('Cash','Asset'), A('Exp','Expense')], [T('1','Cash','Exp',2000)]);
ok(abn(R,'Exp')?.side === 'credit', 'Test 6 Abnormal expense: Exp has a credit balance');
R = run([A('Cash','Asset'), A('Sales','Income')], [T('1','Cash','Sales',10000), T('2','Sales','Cash',4000)]);
ok(!abn(R,'Sales') && R.end.Sales === 6000, 'Partly reversed income (credit 10,000, debit 4,000) is still normal: 6,000');
// The reported data: entries sit on the opposite side of the account's normal balance
const acc = [A('Cash','Asset'), A('Groceries','Expense'), A('Maint','Expense'), A('Pay','Income'), A('utang','Liability'), A('meralco','Liability'), A('tubig','Liability'), A('OBE','Equity',{system:true})];
const tx = [T('e1','Cash','utang',110000), T('e2','Pay','Cash',45000), T('e3','Cash','Groceries',4000), T('e4','Cash','OBE',3000), T('e5','Maint','meralco',1500), T('e6','Maint','tubig',700), T('e7','Maint','OBE',3800)];
R = run(acc, tx);
ok(R.tb.D === 123000 && R.tb.C === 123000, 'Reported data: Trial Balance balanced 123,000 / 123,000');
ok(R.end.Pay === -45000 && R.end.Groceries === -4000 && R.income === -45000, 'Reported data: formulas give Pay -45,000 and Groceries -4,000 because Pay is DEBITED and Groceries CREDITED');
ok(abn(R,'Pay') && abn(R,'Groceries') && !abn(R,'Maint') && abn(R,'Pay').entries[0].id === 'e2', 'Reported data: both accounts flagged with the entries responsible');
ok(R.assets === 72000 && R.liab === 112200, 'Reported data: assets 72,000; liabilities 112,200');
// After the user reverses the two backwards entries (nothing is changed automatically)
const fixed = tx.map(x => x.id === 'e2' ? T('e2','Cash','Pay',45000) : x.id === 'e3' ? T('e3','Groceries','Cash',4000) : x);
R = run(acc, fixed);
ok(R.income === 45000 && R.expense === 10000 && R.income - R.expense === 35000 && !R.issues.length, 'Corrected direction: income 45,000, expenses 10,000, net income 35,000, no warnings');
ok(R.expBy.map(o => Math.round(o.v / R.expPos * 100)).join() === '60,40' && R.expBy[0].name === 'Maint', 'Expense shares 60% / 40%, never above 100%');
ok(R.incBy.length === 1 && R.incBy[0].v === 45000 && R.incPos === 45000, 'Income breakdown: Pay 45,000 (100%)');
ok(R.assets === R.liab + R.equity && R.tb.D === R.tb.C, 'Balance sheet and Trial Balance still balance');
console.log(fails ? fails + ' FAILURES' : 'ALL CHECKS PASSED'); process.exit(fails ? 1 : 0);
